# inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - 'config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '()'
    '%q': '()'
    '%Q': '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '()'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'
