language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - export RUBY_VERSION=$(ruby --version)
before_script:
  - bundle exec rake db:test:prepare --trace
services:
  - postgresql
  - redis-server
addons:
  postgresql: '9.4'
env:
  global:
    - DATABASE_TEST_URL=postgres://postgres:@localhost/travis_ci_test?pool=5
    - SECRET_KEY_BASE=secret_key
notifications:
  email: false
